export class SectionB2 {
  occupationalSunExposure: boolean;
  occupationalSunExposureType: string;
  occupationalSunExposureHours: string;
  occupationalSunExposureDays: string;
  occupationalSunExposureMonths: string;
  occupationalSunExposureYears: string;
  recreationalSunExposure: boolean;
  recreationalSunExposureType: string;
  recreationalSunExposureHours: string;
  recreationalSunExposureDays: string;
  recreationalSunExposureMonths: string;
  recreationalSunExposureYears: string;
  intermittentSunExposure: string;
  intermittentExposureChildhoodWeeks: string;
  intermittentExposureChildhoodHours: string;
  intermittentExposureAdolescenceWeeks: string;
  intermittentExposureAdolescenceHours: string;
  intermittentExposureAdulthoodWeeks: string;
  intermittentExposureAdulthoodHours: string;
  intermittentExposureDiagnosisWeeks: string;
  intermittentExposureDiagnosisHours: string;
  lastIntenseExposure: string;
  sunburnsLess18: string;
  sunburnsGreater17: string;
  sunburnsMelanomaSite: string;
  sunburnsLast5: string;
  less18SunburnsNumber: string;
  greater17SunburnsNumber: string;
  last5SunburnsNumber: string;
  sunscreenPercentageChildhood: string;
  sunscreenTypeChildhood: string;
  sunscreenPercentageAdolescence: string;
  sunscreenTypeAdolescence: string;
  sunscreenPercentageAdulthood: string;
  sunscreenTypeAdulthood: string;
  sunscreenPercentageMelanoma: string;
  sunscreenTypeMelanoma: string;
  sunlamps: boolean;
  numberSunlamps: string;
  ageFirstSunlamps: string;
  ageLastSunlamps: string;


  constructor(form?) {
    if (form) {
      this.occupationalSunExposure = form.value.occupationalSunExposure;
      this.occupationalSunExposureType = form.value.occupationalSunExposureType;
      this.occupationalSunExposureHours = form.value.occupationalSunExposureHours;
      this.occupationalSunExposureDays = form.value.occupationalSunExposureDays;
      this.occupationalSunExposureMonths = form.value.occupationalSunExposureMonths;
      this.occupationalSunExposureYears = form.value.occupationalSunExposureYears;
      this.recreationalSunExposure = form.value.recreationalSunExposure;
      this.recreationalSunExposureType = form.value.recreationalSunExposureType;
      this.recreationalSunExposureHours = form.value.recreationalSunExposureHours;
      this.recreationalSunExposureDays = form.value.recreationalSunExposureDays;
      this.recreationalSunExposureMonths = form.value.recreationalSunExposureMonths;
      this.recreationalSunExposureYears = form.value.recreationalSunExposureYears;
      this.intermittentSunExposure = form.value.intermittentSunExposure;
      this.intermittentExposureChildhoodWeeks = form.value.intermittentExposureChildhoodWeeks;
      this.intermittentExposureChildhoodHours = form.value.intermittentExposureChildhoodHours;
      this.intermittentExposureAdolescenceWeeks = form.value.intermittentExposureAdolescenceWeeks;
      this.intermittentExposureAdolescenceHours = form.value.intermittentExposureAdolescenceHours;
      this.intermittentExposureAdulthoodWeeks = form.value.intermittentExposureAdulthoodWeeks;
      this.intermittentExposureAdulthoodHours = form.value.intermittentExposureAdulthoodHours;
      this.intermittentExposureDiagnosisWeeks = form.value.intermittentExposureDiagnosisWeeks;
      this.intermittentExposureDiagnosisHours = form.value.intermittentExposureDiagnosisHours;
      this.lastIntenseExposure = form.value.lastIntenseExposure;
      this.sunburnsLess18 = form.value.sunburnsLess18;
      this.sunburnsGreater17 = form.value.sunburnsGreater17;
      this.sunburnsMelanomaSite = form.value.sunburnsMelanomaSite;
      this.sunburnsLast5 = form.value.sunburnsLast5;
      this.less18SunburnsNumber = form.value.less18SunburnsNumber;
      this.greater17SunburnsNumber = form.value.greater17SunburnsNumber;
      this.last5SunburnsNumber = form.value.last5SunburnsNumber;
      this.sunscreenPercentageChildhood = form.value.sunscreenPercentageChildhood;
      this.sunscreenTypeChildhood = form.value.sunscreenTypeChildhood;
      this.sunscreenPercentageAdolescence = form.value.sunscreenPercentageAdolescence;
      this.sunscreenTypeAdolescence = form.value.sunscreenTypeAdolescence;
      this.sunscreenPercentageAdulthood = form.value.sunscreenPercentageAdulthood;
      this.sunscreenTypeAdulthood = form.value.sunscreenTypeAdulthood;
      this.sunscreenPercentageMelanoma = form.value.sunscreenPercentageMelanoma;
      this.sunscreenTypeMelanoma = form.value.sunscreenTypeMelanoma;
      this.sunlamps = form.value.sunlamps;
      this.numberSunlamps = form.value.numberSunlamps;
      this.ageFirstSunlamps = form.value.ageFirstSunlamps;
      this.ageLastSunlamps = form.value.ageLastSunlamps;
    } else {
      this.occupationalSunExposure = false;
      this.occupationalSunExposureType = '';
      this.occupationalSunExposureHours = '';
      this.occupationalSunExposureDays = '';
      this.occupationalSunExposureMonths = '';
      this.occupationalSunExposureYears = '';
      this.recreationalSunExposure = false;
      this.recreationalSunExposureType = '';
      this.recreationalSunExposureHours = '';
      this.recreationalSunExposureDays = '';
      this.recreationalSunExposureMonths = '';
      this.recreationalSunExposureYears = '';
      this.intermittentSunExposure = '';
      this.intermittentExposureChildhoodWeeks = '';
      this.intermittentExposureChildhoodHours = '';
      this.intermittentExposureAdolescenceWeeks = '';
      this.intermittentExposureAdolescenceHours = '';
      this.intermittentExposureAdulthoodWeeks = '';
      this.intermittentExposureAdulthoodHours = '';
      this.intermittentExposureDiagnosisWeeks = '';
      this.intermittentExposureDiagnosisHours = '';
      this.lastIntenseExposure = '';
      this.sunburnsLess18 = form.value.sunburnsLess18;
      this.sunburnsGreater17 = form.value.sunburnsGreater17;
      this.sunburnsMelanomaSite = '';
      this.sunburnsLast5 = form.value.sunburnsLast5;
      this.less18SunburnsNumber = '';
      this.greater17SunburnsNumber = '';
      this.last5SunburnsNumber = '';
      this.sunscreenPercentageChildhood = '';
      this.sunscreenTypeChildhood = '';
      this.sunscreenPercentageAdolescence = '';
      this.sunscreenTypeAdolescence = '';
      this.sunscreenPercentageAdulthood = '';
      this.sunscreenTypeAdulthood = '';
      this.sunscreenPercentageMelanoma = '';
      this.sunscreenTypeMelanoma = '';
      this.sunlamps = false;
      this.numberSunlamps = '';
      this.ageFirstSunlamps = '';
      this.ageLastSunlamps = '';
    }
  }
}
